# name: build-release-$(git rev-parse --short "$GITHUB_SHA")
run-name: Build-Release Num. ${{ github.run_number }}

on:
  workflow_dispatch:
    # inputs:
    #   configuration:
    #     description: 'Compiler configuration preset'
    #     required: false
    #     default: 'Debug'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #   - '**.vb'
  #   - '**.vbproj'
  #   - '**.cs'
  #   - '**.csproj'
  #   - '**.resx'

env:
  DOTNET_VERSION: '4.7.2' # The .NET SDK version to use
  SLN_FILE: AGauge/AGauge.sln
  OUTPUT: AGauge/bin/Release
  CONFIG: Release

jobs:
  build:

    name: debug-build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # Should have MSBuild.
    steps:
    # Make MSBuild available from $PATH.
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Checkout Code
      uses: actions/checkout@v3

    # - name: Restore Packages
    #   run: msbuild -t:restore

    - name: Build solution
      run: msbuild $env:SLN_FILE -p:Configuration=$env:CONFIG

    - name: Get AssemblyVersion generated by msbuild
      id: getversion
      uses: berglie/assembly-version/get@v1
      with:
        directory: ${{ env.OUTPUT }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('AGauge-v{0}', steps.getversion.outputs.version) }}
        if-no-files-found: error
        path: ${{ env.OUTPUT }}
          