name: build-debug

on:
  workflow_dispatch:

  # Cause GH to build only for modified code files in a PR, but not when a tag is specified (https://stackoverflow.com/a/71879890/530172)
  pull_request:
    paths:
    - "**.cs"
    - "**.csproj"

env:
  PRIMARY_FOLDER: AGauge

jobs:
  build-debug:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4

      - name: Build Project
        run: >
          dotnet build ${{ env.PRIMARY_FOLDER }}\AGaugeClassic.csproj
          --nologo
          -c Debug
          -p:Version=1.0.0.0

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AGauge-Debug-CIBuild_${{ github.run_number }}
          path: ${{ env.PRIMARY_FOLDER }}\bin\Debug
          if-no-files-found: error
